"""A scan of ``demo/`` through the API, end to end — the build step 4 exit test.

The demo environment (build step 3) is a scan target as well as a lab: point a
``files`` scan at the directory and the certificate and config collectors have
everything they need with no Docker running at all.

What is asserted here is only what the *committed* part of the tree guarantees.
``demo/certs/`` is generated by ``gen_certs.sh`` and gitignored, so the
certificate assertions run when it exists and are skipped when it does not —
which is honest, and is why ``tests/test_collectors_certs.py`` carries its own
committed copy of the weak certificate rather than depending on this.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.models.enums import CollectorName


def approve_everything(client, scan_id: str) -> dict:
    tree = client.get(f"/api/scans/{scan_id}/files")
    assert tree.status_code == 200, tree.text

    paths: list[str] = []

    def walk(node: dict) -> None:
        for child in node["children"]:
            if child["type"] == "file":
                paths.append(child["path"])
            else:
                walk(child)

    walk(tree.json()["root"])
    response = client.post(f"/api/scans/{scan_id}/approve", json={"paths": paths})
    assert response.status_code == 200, response.text
    return response.json()


@pytest.fixture
def demo_scan(client, demo_dir: Path) -> dict:
    created = client.post(
        "/api/scans",
        json={
            "mode": "files",
            "source_type": "folder",
            "source_ref": str(demo_dir),
            # demo/README.md: at X=20 the Mosca inequality actually bites, which
            # is what makes wave_1 and wave_2 populate in step 9.
            "data_lifetime_years": 20,
        },
    )
    assert created.status_code == 201, created.text
    return approve_everything(client, created.json()["id"])


def test_a_demo_scan_produces_findings_from_both_collectors(demo_scan) -> None:
    assert demo_scan["status"] == "complete"
    assert demo_scan["finding_count"] > 0

    runs = {run["name"]: run for run in demo_scan["collectors"]}
    assert set(runs) == {CollectorName.CERTS.value, CollectorName.CONFIG.value}
    assert all(run["error"] is None for run in runs.values())

    # The config half is guaranteed by the committed tree: two nginx.conf, two
    # openssl.cnf, an sshd_config and a java.security.
    assert runs[CollectorName.CONFIG.value]["finding_count"] > 0


def test_a_demo_scan_finds_the_generated_certificates(demo_scan, demo_dir: Path) -> None:
    if not (demo_dir / "certs" / "weak.crt").is_file():
        pytest.skip("demo/certs is generated and gitignored; run demo/gen_certs.sh")

    runs = {run["name"]: run for run in demo_scan["collectors"]}
    assert runs[CollectorName.CERTS.value]["finding_count"] > 0


def test_a_demo_scan_reads_only_what_was_approved(client, demo_dir: Path) -> None:
    """Approving one file means one file is read, however much else is in the tree."""
    created = client.post(
        "/api/scans",
        json={
            "mode": "files",
            "source_type": "folder",
            "source_ref": str(demo_dir),
            "data_lifetime_years": 20,
        },
    )
    scan_id = created.json()["id"]

    response = client.post(
        f"/api/scans/{scan_id}/approve", json={"paths": ["weak-nginx/openssl.cnf"]}
    )

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["approved_count"] == 1
    runs = {run["name"]: run for run in body["collectors"]}
    # Only the openssl.cnf was in scope, so only the config collector saw anything.
    assert runs[CollectorName.CONFIG.value]["finding_count"] == 2
    assert runs[CollectorName.CERTS.value]["finding_count"] == 0
