"""Binary collector — SPEC.md §7.2.

The demo binary is generated by the compose stack and gitignored, so a copy is
committed under ``tests/data`` (see its README) and the tests prefer the demo's
own build when it exists — the same arrangement the certificate tests use.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.collectors.binary import (
    BinaryCollector,
    is_elf,
    library_from_soname,
)
from app.collectors.binary_yara import YaraBinaryCollector
from app.core.advisor import ScanObservations
from app.core.normalizer import normalize
from app.models.enums import (
    CollectorName,
    Confidence,
    Primitive,
    ScanMode,
    ScanStatus,
    SourceLayer,
    SourceType,
)
from app.models.finding import Finding
from app.models.scan import Scan
from tests.conftest import DEMO_DIR, TEST_DATA_DIR

BINARY = "bin/cryptodemo"


@pytest.fixture(scope="session")
def elf_bytes() -> bytes:
    generated = DEMO_DIR / "cbin" / "build" / "cryptodemo"
    source = generated if generated.is_file() else TEST_DATA_DIR / "cryptodemo-openssl1.1.elf"
    return source.read_bytes()


@pytest.fixture
def findings(scan_context, elf_bytes):
    ctx = scan_context(
        {
            BINARY: elf_bytes,
            "README.md": "# not an ELF\n",
            "certs/server.crt": "-----BEGIN CERTIFICATE-----\n",
            "bin/truncated": b"\x7fELF" + b"\x01" * 40,
        }
    )
    return BinaryCollector().collect(ctx)


def with_observation(findings, observation: str):
    return [f for f in findings if f.evidence_raw.get("observation") == observation]


# --------------------------------------------------------------------------- #
# DT_NEEDED — the advisor's input
# --------------------------------------------------------------------------- #


def test_the_demo_binary_produces_a_libcrypto_dependency_finding(findings) -> None:
    """§7.2's required test. ``libcrypto.so.1.1`` is what blocks ML-KEM in the demo."""
    linked = with_observation(findings, "linked_library")

    assert [f.algorithm_name for f in linked] == ["libcrypto.so.1.1"]
    finding = linked[0]
    assert finding.evidence_raw["library"] == "openssl"
    assert finding.evidence_raw["version"] == "1.1"
    assert finding.evidence_raw["version_precision"] == "soname"
    assert finding.confidence is Confidence.HIGH
    assert finding.source_layer is SourceLayer.ARTIFACT
    assert finding.collector is CollectorName.BINARY
    assert finding.evidence_location == BINARY


def test_libc_is_not_a_crypto_library(findings) -> None:
    assert not any("libc.so" in f.algorithm_name for f in findings)


def test_the_version_banner_carries_the_release_the_soname_lacks(findings) -> None:
    """``OPENSSL_VERSION_TEXT`` in .rodata — demo/README.md §G's "useful wrinkle"."""
    banners = with_observation(findings, "library_version_string")

    assert len(banners) == 1
    banner = banners[0]
    assert banner.evidence_raw["library"] == "openssl"
    assert banner.evidence_raw["version"] == "1.1.1f"
    assert banner.evidence_raw["text"].startswith("OpenSSL 1.1.1f")
    # A string, so medium — the advisor trusts it beside the soname, not alone.
    assert banner.confidence is Confidence.MEDIUM


def test_soname_parsing_never_rounds() -> None:
    assert library_from_soname("libcrypto.so.1.1") == ("openssl", "1.1")
    assert library_from_soname("libssl.so.3") == ("openssl", "3")
    assert library_from_soname("libcrypto.so.1.0.0") == ("openssl", "1.0.0")
    assert library_from_soname("libcrypto.so") == ("openssl", None)
    assert library_from_soname("libgnutls.so.30") == ("gnutls", "30")
    assert library_from_soname("libc.so.6") is None


# --------------------------------------------------------------------------- #
# Symbols — proof of capability
# --------------------------------------------------------------------------- #


def test_dynamic_symbols_prove_the_algorithms_the_binary_can_call(findings) -> None:
    symbols = {
        (f.algorithm_name, f.primitive, f.mode): f for f in with_observation(findings, "dynamic_symbol")
    }

    md5 = symbols[("MD5", Primitive.HASH, None)]
    assert md5.evidence_raw["symbols"] == ["MD5_Final", "MD5_Init", "MD5_Update"]
    assert md5.confidence is Confidence.HIGH

    assert ("SHA-1", Primitive.HASH, None) in symbols
    assert symbols[("SHA-1", Primitive.HASH, None)].evidence_raw["symbols"] == ["EVP_sha1"]

    rsa = symbols[("RSA", Primitive.UNKNOWN, None)]
    assert "RSA_generate_key_ex" in rsa.evidence_raw["symbols"]

    des_ecb = symbols[("DES", Primitive.CIPHER, "ECB")]
    assert des_ecb.evidence_raw["symbols"] == ["DES_ecb_encrypt"]
    assert ("DES", Primitive.CIPHER, None) in symbols  # DES_set_key_unchecked


def test_one_capability_is_one_finding(findings) -> None:
    """MD5_Init, MD5_Update and MD5_Final are one capability, not three rows."""
    md5 = [f for f in with_observation(findings, "dynamic_symbol") if f.algorithm_name == "MD5"]
    assert len(md5) == 1


# --------------------------------------------------------------------------- #
# .rodata — hints, at medium
# --------------------------------------------------------------------------- #


def test_rodata_strings_that_name_algorithms_are_reported_at_medium(findings) -> None:
    strings = {f.algorithm_name: f for f in with_observation(findings, "rodata_string")}

    for expected in (
        "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        "TLS_RSA_WITH_RC4_128_MD5",
        "sha1WithRSAEncryption",
        "AES-128-CBC",
        "AES-256-GCM",
    ):
        assert expected in strings, sorted(strings)
        assert strings[expected].confidence is Confidence.MEDIUM

    # Format strings and record ids are not algorithms.
    assert "demo-settlement-0001" not in strings
    assert not any(name.startswith("suite") for name in strings)
    # The version banner is its own observation, not a string finding.
    assert not any(name.startswith("OpenSSL") for name in strings)


# --------------------------------------------------------------------------- #
# Non-ELF input
# --------------------------------------------------------------------------- #


def test_non_elf_files_are_skipped_without_error(findings) -> None:
    """§7.2's required test. A README and a certificate produce nothing and break nothing."""
    locations = {f.evidence_location for f in findings}
    assert locations == {BINARY}


def test_a_truncated_elf_costs_itself_and_nothing_else(findings) -> None:
    assert not any(f.evidence_location == "bin/truncated" for f in findings)
    assert with_observation(findings, "linked_library")


def test_the_sniff_is_four_bytes(tmp_path: Path) -> None:
    (tmp_path / "elf").write_bytes(b"\x7fELF\x02\x01")
    (tmp_path / "text").write_text("ELF but not really\n", encoding="utf-8")
    assert is_elf(tmp_path / "elf")
    assert not is_elf(tmp_path / "text")
    assert not is_elf(tmp_path / "missing")


def test_the_yara_stub_implements_the_interface_and_finds_nothing(scan_context, elf_bytes) -> None:
    ctx = scan_context({BINARY: elf_bytes})
    collector = YaraBinaryCollector()
    assert collector.name is CollectorName.BINARY
    assert collector.collect(ctx) == []


# --------------------------------------------------------------------------- #
# What the advisor sees
# --------------------------------------------------------------------------- #


def test_the_binary_evidence_is_what_the_advisor_reads(db_session, findings) -> None:
    """The soname and the banner from one binary reach §11's feasibility check together."""
    scan = Scan(
        mode=ScanMode.FILES,
        source_type=SourceType.FOLDER,
        source_ref="/tmp/whatever",
        data_lifetime_years=20,
        policy_version="2026.09",
        status=ScanStatus.RUNNING,
    )
    db_session.add(scan)
    db_session.flush()
    normalize(db_session, scan.id, findings)
    rows = list(db_session.scalars(Finding.__table__.select().where(Finding.scan_id == scan.id)))

    stored = db_session.query(Finding).filter(Finding.scan_id == scan.id).all()
    seen = ScanObservations(stored).libraries(BINARY, "openssl")

    assert sorted((o.version, o.observation) for o in seen) == [
        ("1.1", "linked_library"),
        ("1.1.1f", "library_version_string"),
    ]
    assert rows  # the normalizer stored every observation, unresolved names included
