"""initial schema

The eight tables of SPEC.md §5, plus provenance_blobs from §7.6.

Column types are Postgres-first: uuid primary keys, jsonb payloads, timestamptz,
and native ENUM types. The SQLite variants exist only so the test suite can run
without a database server.

Revision ID: 51ab36a72007
Revises: 
Create Date: 2026-09-03 01:24:01.225500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ab36a72007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('probe_only', 'files', 'files_and_probe', name='scan_mode'), nullable=False),
    sa.Column('source_type', sa.Enum('folder', 'github', 'docker_image', 'none', name='source_type'), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('probe_targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('data_lifetime_years', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('staging', 'awaiting_approval', 'running', 'complete', 'partial', 'failed', name='scan_status'), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('collector', sa.Enum('code', 'binary', 'certs', 'config', 'network', 'cbom_import', name='collector_name'), nullable=False),
    sa.Column('algorithm_name', sa.Text(), nullable=False),
    sa.Column('algorithm_oid', sa.Text(), nullable=True),
    sa.Column('algorithm_family', sa.Text(), nullable=True),
    sa.Column('primitive', sa.Enum('key_exchange', 'signature', 'hash', 'cipher', 'protocol', 'unknown', name='primitive'), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('protocol_version', sa.Text(), nullable=True),
    sa.Column('evidence_location', sa.Text(), nullable=True),
    sa.Column('evidence_raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('source_layer', sa.Enum('live', 'artifact', 'config', 'source', name='source_layer'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)

    op.create_table('provenance_blobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('raw_document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance_blobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_blobs_scan_id'), ['scan_id'], unique=False)

    op.create_table('scan_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'path', name='uq_scan_files_scan_path')
    )
    with op.batch_alter_table('scan_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_files_scan_id'), ['scan_id'], unique=False)

    op.create_table('alignment_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('live_finding_id', sa.Uuid(), nullable=False),
    sa.Column('config_finding_id', sa.Uuid(), nullable=False),
    sa.Column('asset_key', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['config_finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['live_finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alignment_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alignment_notes_scan_id'), ['scan_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('recommended', 'blocked', 'no_path', 'unknown', name='recommendation_status'), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('hybrid_target', sa.Text(), nullable=True),
    sa.Column('action_class', sa.Enum('config', 'library_upgrade', 'code_change', 'hardware', name='action_class'), nullable=True),
    sa.Column('prerequisites', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_finding_id'), ['finding_id'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('x_years', sa.Integer(), nullable=True),
    sa.Column('y_years', sa.Integer(), nullable=True),
    sa.Column('z_years', sa.Integer(), nullable=True),
    sa.Column('urgency_years', sa.Integer(), nullable=True),
    sa.Column('wave', sa.Enum('wave_0', 'wave_1', 'wave_2', 'wave_3', 'verify', name='wave'), nullable=False),
    sa.Column('rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_finding_id'), ['finding_id'], unique=False)

    op.create_table('verdicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.Enum('broken_now', 'quantum_vulnerable', 'quantum_safe', 'hygiene', 'unknown', name='verdict'), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdicts_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


#: Native Postgres ENUM types created implicitly by the CREATE TABLEs above.
#: op.drop_table does not remove them, so downgrade has to do it explicitly.
ENUM_TYPE_NAMES = (
    "scan_mode",
    "source_type",
    "scan_status",
    "collector_name",
    "primitive",
    "confidence",
    "source_layer",
    "recommendation_status",
    "action_class",
    "wave",
    "verdict",
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdicts_finding_id'))

    op.drop_table('verdicts')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_finding_id'))

    op.drop_table('risk_scores')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_finding_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('alignment_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alignment_notes_scan_id'))

    op.drop_table('alignment_notes')
    with op.batch_alter_table('scan_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_files_scan_id'))

    op.drop_table('scan_files')
    with op.batch_alter_table('provenance_blobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_blobs_scan_id'))

    op.drop_table('provenance_blobs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))

    op.drop_table('findings')
    op.drop_table('scans')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for type_name in ENUM_TYPE_NAMES:
            sa.Enum(name=type_name).drop(bind, checkfirst=True)
